### ISSUE TITLE
Tx Interface

### ISSUE THREAD

**Issue by jaeykim** [eth4nos/go-ethereum#2]
Restoration Tx를 만들기 위한 interface 구현

Web3.js와 Geth에서 full node가
1. restoration에 필요한 정보들을 제공
e.g) web3.eth.getRestorationProof(account)
2. 제공한 정보들을 Tx에 담아 전파
to address를 특정 주소로 했을 때 restoration routine이 실행되도록

**Comment by lukepark327** [comment]
`EIP-1186`로부터 Proof와 Verify는 web3.js 1.0.0 스펙에 포함

* https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1186.md

* https://web3js.readthedocs.io/en/1.0/web3-eth.html#getproof

* https://web3js.readthedocs.io/en/1.0/web3-eth.html#eth-getstorageat
